services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: amongus
    container_name: mongo
    volumes:
      - wabisabi_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
  mongoexpress:
    restart: always
    container_name: mongo_ui
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: amongus
      ME_CONFIG_MONGODB_PORT: 8081
      ME_CONFIG_MONGODB_SERVER: mongo
      #ME_CONFIG_MONGODB_URL: mongodb://admin:amogus@mongo:27017/
    depends_on:
      - mongo
volumes:
  wabisabi_db:
